from pymongo import MongoClient

# Create a client
client = MongoClient('mongodb://localhost:27017/')

# Access the 'mydatabase' database
db = client['mydatabase']

# Access the 'games' collection
games = db['games']

# JSON data for a game, will be generated by ryan
game = {
  "game_id": 2,
  "level_number": 3,
  "player_index": 5,
  "players": [
    {
      "name": "Player4",
      "password": "password123",
      "streak": 2,
      "duck_count": 0,
      "score": 250
    }
  ]
}

def insert_game(game):
  # Insert the game into the 'games' collection
  result = games.update_one({"game_id": game["game_id"]}, {"$set": game}, upsert=True)
  return result

# # Print the id of the inserted document
# print("Inserted game with id %s" % result.upserted_id)

def find_game_by_id(game_id):
  # Find the game with the specified game_id
  game = games.find_one({"game_id": game_id})
  return game

def get_player_scores():
  # Initialize the player_scores dictionary
  player_scores = {}

  # for each game_id, print the player names and scores
  for game in games.find():
    # print("Game %s" % game["game_id"])
    for player in game["players"]:
      # Store the player names and scores in the dictionary
      player_scores[player["name"]] = player["score"]
    # print(player_scores)
  return player_scores

def get_player_info():
  # Initialize the player_info dictionary
  player_info = {}

  # for each game_id, print the player names and scores
  for game in games.find():
    # print("Game %s" % game["game_id"])
    for player in game["players"]:
      # Store the player names and scores in the dictionary
      player_info[player["name"]] = {
        "streak": player["streak"],
        "duck_count": player["duck_count"],
        "score": player["score"]
      }
    # print(player_info)
  return player_info

